### ISSUE TITLE
install rrdtool error

### ISSUE THREAD

**Issue by yangyang-zhang** [commx/python-rrdtool#22]
Environment: Centos7.3  Python2.7.5
1. yum -y install gcc* rrdtool-devel
2. pip install rrdtool
```
Collecting rrdtool
  Using cached rrdtool-0.1.11.tar.gz
Building wheels for collected packages: rrdtool
  Running setup.py bdist_wheel for rrdtool ... error
  Complete output from command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-QPpgMw/rrdtool/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpWNznqJpip-wheel- --python-tag cp27:
  tmp/tmp_python_rrdtoolZwdfwE/test_rrdtool.o: In function `main':
  /tmp/tmp_python_rrdtoolZwdfwE/test_rrdtool.c:6: undefined reference to `rrd_fetch_cb_register'
  collect2: error: ld returned 1 exit status
  Warning: Seems like your rrdtool version does not support fetch callbacks, recompiling.running bdist_wheel
  running build
  running build_ext
  building 'rrdtool' extension
  creating build
  creating build/temp.linux-x86_64-2.7
  gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DPACKAGE_VERSION="0.1.11" -I/tmp/pip-build-QPpgMw/rrdtool -I/usr/local/include -I/usr/include/python2.7 -c rrdtoolmodule.c -o build/temp.linux-x86_64-2.7/rrdtoolmodule.o
  creating build/lib.linux-x86_64-2.7
  gcc -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-2.7/rrdtoolmodule.o -L/usr/local/lib -L/usr/lib64 -lrrd -lpython2.7 -o build/lib.linux-x86_64-2.7/rrdtool.so
  /usr/bin/ld: /usr/local/lib/libpython2.7.a(capsule.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
  /usr/local/lib/libpython2.7.a: error adding symbols: Bad value
  collect2: error: ld returned 1 exit status
  error: command 'gcc' failed with exit status 1

```

**Comment by commx** [comment]
Looks like something is broken on your system. I tried building here with a fresh CentOS 7.3 docker container and it worked out of the box after installing the dependencies:

`yum install -y python-devel rrdtool-devel gcc`

Relevant parts of the pip install (had to install python2-pip first, available from epel repositories):

`pip install rrdtool -v`

```
    running build
    running build_ext
    building 'rrdtool' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DPACKAGE_VERSION="0.1.11" -I/tmp/pip-build-9SUSFu/rrdtool -I/usr/local/include -I/usr/include/python2.7 -c rrdtoolmodule.c -o build/temp.linux-x86_64-2.7/rrdtoolmodule.o
    creating build/lib.linux-x86_64-2.7
    gcc -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-2.7/rrdtoolmodule.o -L/usr/local/lib -L/usr/lib64 -lrrd -lpython2.7 -o build/lib.linux-x86_64-2.7/rrdtool.so
    running install_lib
    copying build/lib.linux-x86_64-2.7/rrdtool.so -> /usr/lib64/python2.7/site-packages
    running install_egg_info
    running egg_info
    writing rrdtool.egg-info/PKG-INFO
    writing top-level names to rrdtool.egg-info/top_level.txt
    writing dependency_links to rrdtool.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'rrdtool.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'rrdtool.egg-info/SOURCES.txt'
    Copying rrdtool.egg-info to /usr/lib64/python2.7/site-packages/rrdtool-0.1.11-py2.7.egg-info
    running install_scripts
    writing list of installed files to '/tmp/pip-oRvcCE-record/install-record.txt'
done
  Removing source in /tmp/pip-build-9SUSFu/rrdtool
Successfully installed rrdtool-0.1.11
Cleaning up...
```

You could try recompiling it with PIC, such as

`CFLAGS=-fPIC pip install rrdtool -v`

**Comment by yangyang-zhang** [comment]
Thank you， but when i execute CFLAGS=-fPIC pip install rrdtool -v , appear same errors

```

 gcc -pthread -shared -Wl,-z,relro -fPIC build/temp.linux-x86_64-2.7/rrdtoolmodule.o -L/usr/local/lib -L/usr/lib64 -lrrd -lpython2.7 -o build/lib.linux-x86_64-2.7/rrdtool.so
  /usr/bin/ld: /usr/local/lib/libpython2.7.a(capsule.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
  /usr/local/lib/libpython2.7.a: error adding symbols: Bad value
  collect2: error: ld returned 1 exit status
  error: command 'gcc' failed with exit status 1
error
  Failed building wheel for rrdtool
  Running setup.py clean for rrdtool
  Running command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Jpb52K/rrdtool/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all
  tmp/tmp_python_rrdtool3EEtL3/test_rrdtool.o: In function `main':
  /tmp/tmp_python_rrdtool3EEtL3/test_rrdtool.c:6: undefined reference to `rrd_fetch_cb_register'
  collect2: error: ld returned 1 exit status
  Warning: Seems like your rrdtool version does not support fetch callbacks, recompiling.running clean
  removing 'build/temp.linux-x86_64-2.7' (and everything under it)
  removing 'build/lib.linux-x86_64-2.7' (and everything under it)
  'build/bdist.linux-x86_64' does not exist -- can't clean it
  'build/scripts-2.7' does not exist -- can't clean it
  removing 'build'
Failed to build rrdtool
Installing collected packages: rrdtool
  Running setup.py install for rrdtool ...     Running command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Jpb52K/rrdtool/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-nFPtz6-record/install-record.txt --single-version-externally-managed --compile
    tmp/tmp_python_rrdtoolmewC0o/test_rrdtool.o: In function `main':
    /tmp/tmp_python_rrdtoolmewC0o/test_rrdtool.c:6: undefined reference to `rrd_fetch_cb_register'
    collect2: error: ld returned 1 exit status
    Warning: Seems like your rrdtool version does not support fetch callbacks, recompiling.running install
    running build
    running build_ext
    building 'rrdtool' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -fPIC -DPACKAGE_VERSION="0.1.12" -I/tmp/pip-build-Jpb52K/rrdtool -I/usr/local/include -I/usr/include/python2.7 -c rrdtoolmodule.c -o build/temp.linux-x86_64-2.7/rrdtoolmodule.o
    creating build/lib.linux-x86_64-2.7
    gcc -pthread -shared -Wl,-z,relro -fPIC build/temp.linux-x86_64-2.7/rrdtoolmodule.o -L/usr/local/lib -L/usr/lib64 -lrrd -lpython2.7 -o build/lib.linux-x86_64-2.7/rrdtool.so
    /usr/bin/ld: /usr/local/lib/libpython2.7.a(capsule.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
    /usr/local/lib/libpython2.7.a: error adding symbols: Bad value
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1
error
Cleaning up...
  Removing source in /tmp/pip-build-Jpb52K/rrdtool
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Jpb52K/rrdtool/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-nFPtz6-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Jpb52K/rrdtool/
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/usr/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Jpb52K/rrdtool/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-nFPtz6-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Jpb52K/rrdtool/

```
